"""add all tables

Revision ID: 34c46b41e0fc
Revises: fd2510d5234a
Create Date: 2026-07-30 13:58:46.313858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c46b41e0fc'
down_revision: Union[str, Sequence[str], None] = 'fd2510d5234a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('serving_size', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('serving_unit', sa.String(length=30), nullable=False),
    sa.Column('calories', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('carbs', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fiber', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('sugar', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_table('custom_foods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('serving_size', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('serving_unit', sa.String(length=30), nullable=False),
    sa.Column('calories', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('carbs', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fiber', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('sugar', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('total_calories', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_protein', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_carbs', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_fat', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_fiber', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_sugar', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('ai_provider', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('ai_status', sa.String(length=20), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_meal_date'), 'meals', ['meal_date'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('total_calories', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_protein', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_carbs', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_fat', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_fiber', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('total_sugar', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('height_cm', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('weight_kg', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('activity_level', sa.String(length=50), nullable=False),
    sa.Column('fitness_goal', sa.String(length=50), nullable=False),
    sa.Column('calorie_goal', sa.Integer(), nullable=False),
    sa.Column('protein_goal', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('carbs_goal', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('fat_goal', sa.DECIMAL(precision=6, scale=2), nullable=False),
    sa.Column('water_goal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('water_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('custom_food_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('calories', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('protein', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('carbs', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fat', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('fiber', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('sugar', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['custom_food_id'], ['custom_foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_items_meal_id'), 'meal_items', ['meal_id'], unique=False)
    op.create_table('recipe_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=True),
    sa.Column('custom_food_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['custom_food_id'], ['custom_foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_items')
    op.drop_index(op.f('ix_meal_items_meal_id'), table_name='meal_items')
    op.drop_table('meal_items')
    op.drop_table('water_logs')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_meal_date'), table_name='meals')
    op.drop_table('meals')
    op.drop_table('custom_foods')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
